### PR TITLE
Moved updateConnParams out of onConnect

### LINKED ISSUE #60: Possible connection issue with iPhone
This may or may not come up in your testing but I have found that newer versions of iOS don't seem to like [updateConnParams](https://github.com/doudar/SmartSpin2k/blob/715743afa8b6395a000d38316b4952e424971ce3/src/BLE_Server.cpp#L308) in the server onConnect callback. In my experience lately nRFconnect will fail to connect until that line is removed, it could be due to the parameters I used or it could be a bug in nRFconnect but I thought I'd mention it in case you run into this.

### PR DESCRIPTION
**Pull request by doudar**
Fixes #60

### CODE REVIEW

**Comment by h2zero** [comment]
This looks like a patch I would do, aim to fix one thing and change a bunch of stuff at the same time lol.

1 comment though, I don't think you need the delay, but if your experience says otherwise I would find it interesting. 
Weird dynamic with the server side of NimBLE that I'd like to understand.

**Comment by doudar** [comment]
Oh wow, I didn't actually look at the commit :)

That's ugly isn't it. I did a right click - format document in PIO (autoformat). I'll have to keep that in mind. I'm newish to PIO.

The vTaskDelay() isn't probably needed but since you suggested there could be an issue in the callback, I thought it may be timing related so I figured I could spare 100ms.

**Comment by doudar** [comment]
I just make sure to never use autoformat in the files where I define pretty classes :)

Love/hate. Love the auto indents, hate that it mixed up your intentional spaces.

**Comment by h2zero** [comment]
It's all good as long as the code works haha, only an issue if you break something at the same time in the commit :). 

I think the issue came from calling the updateParams within the callback context, however I'm not sure about that. The delay won't hurt but it may not help either.

**Comment by doudar** [comment]
Fwiw I did a bunch more testing tonight and couldn't get it to fail in either spot. 🤷‍♂️

Here's to heading off a potential issue?

**Comment by h2zero** [comment]
Nice, like I said, it was only in my experience and have not heard of others but good to get ahead of it for sure.

**Pull request merged**
