### PR TITLE
Fixed Typo in pdf

### PR DESCRIPTION
**Pull request by doudar**
Changed reference to M4 bolt to M5 Bolt.
Increased right side case mounting hole to 5.5mm so the bolt slides in easier.

### CODE REVIEW

**Comment by bannus** [comment]
@doudar Any reason not to increase the hole on the left side to 5.5mm as well? It's currently exactly 5mm.

**Comment by doudar** [comment]
> @doudar Any reason not to increase the hole on the left side to 5.5mm as well? It's currently exactly 5mm.

My thinking is that it provides similar locking action to a nylock nut.

**Comment by doudar** [comment]
@eMadman - is this okay to be merged?

**Review by eMadman — APPROVED** [review]
Looks good!

**Pull request merged**
