### PR TITLE
Updated Peloton 7 Flat Insert

### PR DESCRIPTION
**Pull request by doudar**
Discussions #82

### CODE REVIEW

**Comment by doudar** [comment]
Co-Authored by @chaloney

**Review by fireyeti — APPROVED** [review]

**Comment by doudar** [comment]
@kadaan ?

**Comment by kadaan** [comment]
> @kadaan ?

Seriously GitHub…. Allowing to skip GitHub actions for certain folders, but then still requiring the action to merge?!?!  Super lame. 

Let me look into this.

**Comment by kadaan** [comment]
@doudar Ready for you to merge

**Pull request merged**
