### PR TITLE
Update cert.h

### PR DESCRIPTION
**Pull request by eMadman**
Still throws an error when trying to  connect to check for newer firmware

[  6772][E][ssl_client.cpp:36] _handle_error(): [start_ssl_client():263]: (-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
[  6774][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -9984

### CODE REVIEW

**Comment by doudar** [comment]
There's something like a "master" certificate you could look for, also make sure it's for the proper GitHub domain as referenced by the firmware url in settings.h 

I remember having to try a couple different ones when auto updates were first implemented. Possibly @MarkusSchneider has some insight in what certificate to use?

**Comment by eMadman** [comment]
Reverted the changes - after digging, the original is on the correct cert - Github's using 

DigiCert SHA2 High Assurance Server CA

**Comment by eMadman** [comment]
Adding all the Digicert certificates seems to fix it.  Sent it out to two users for testing

**Comment by doudar** [comment]
Can you please add a note in cert.h where you got the new ssl from for future reference?

Also need an update to the changelog. 

Great work!

**Review by doudar — APPROVED** [review]
Approved, but check the notes above before you merge. 

Thanks!

**Comment by MarkusSchneider** [comment]
@eMadman You finally solved it 👍. 
Last time when I created a certificate I got 3 files. I combined all files into one crt file.
I've got a root-ca certificate, intermediate certificate and the new certificate for my application. root-ca certificate and intermediate certificate are necessary to build the chain of trust to a trusted Root CA.

Good work.

**Comment by eMadman** [comment]
Ready to merge - pending feedback from another user before I click it.

**Comment by eMadman** [comment]
I'm comfortable with the changes at this point.  Tested on a couple more units - successful attempts at reaching github and downloads of the HTML files

**Pull request merged**
