### PR TITLE
Added a custom integrated implementation of WifiManager.

### PR DESCRIPTION
**Pull request by doudar**
- Updated builtin.h html color scheme.
- When pages are served, BLE server will slow it's roll.
- Added a custom integrated implementation of WifiManager.
- Removed several BLE scan hard stops in favor of a single loop which waits for the scan to gracefully end.
- Fixed bug where WiFi.getMode() wasn't returning the correct mode and caused slow/no wifi connections in AP mode.
- Repurposed LogComData. Will now not transmit any logging info to WiFi when it's turned off.
- Reworked web pages to start to implement more built in functions.
- Removed style.css (Internal to the program now).

### CODE REVIEW

**Comment by eMadman** [comment]
this commit should probably come with some refactoring.  I jammed in an individual table per line because I couldn't figure out how to incorporate table rows and cells into HTTP_Server_Basic.cpp.

Also needs testing on multiple OSes, browsers and devices because I didn't apply any styling to the tables beyond an inline align=center

**Comment by doudar** [comment]
Fixes #412

**Comment by doudar** [comment]
This is probably going to be depreciated because of Config app. @eMadman , your thoughts?

**Comment by eMadman** [comment]
Agreed.  The wifi manager and hotspot are  fantastic but they cause
difficulty for some users.  Also bypasses risks associated with users
leaving the device in hotspot mode

**Pull request closed without merging**
