### PR TITLE
Fix mDNS dropouts

### PR DESCRIPTION
**Pull request by kadaan**
Fix mDNS dropouts by adding a service text record that gets updated every minute.

Screen Shot 2021-02-24 at 2 47 18 AM

### CODE REVIEW

**Review by doudar — COMMENTED** [review]
"Add" sounds like we keep appending this key value pair to some sort of array.  Are we sure that running MDNS.addServiceTxt("http", "_tcp", "lf", String(mDnsTimer)); repeatedly every minute doesn't cause a memory leak on the ESP32 or cause possible downstream issues with ledgers on local LAN devices? 

Also, every minute seems excessive. Is it required that often in your testing?

**Comment by kadaan** [comment]
`addServiceText` is an add or set, so in our case it is an update. My understanding was that the mDNS resolution stopped working after 2m, so 1m felt safe to try. I’ve left SS2K running all night so we can see how it is doing.

**Comment by doudar** [comment]
> `addServiceText` is an add or set, so in our case it is an update. My understanding was that the mDNS resolution stopped working after 2m, so 1m felt safe to try. I’ve left SS2K running all night so we can see how it is doing.

If you haven't,  you could add in Serial.println(ESP.getFreeHeap()); to monitor memory usage via the serial terminal for debugging.

**Review by doudar — APPROVED** [review]
Moving this into PR-TESTING for ... testing......

**Pull request merged**
