### PR TITLE
Fixed bug where "none" hr still scanned

### PR DESCRIPTION
**Pull request by doudar**
Will probably merge this very soon. There's not much to test.

### CODE REVIEW

**Comment by doudar** [comment]
I just tested on a sim ride in Zwift as well as testing the conditions for scanning or not prior to the ride. It seems good to me. Please review.

**Review by xpectnil — APPROVED** [review]
Looks good

**Comment by xpectnil** [comment]
Looks good, worked for me as well.

**Comment by xpectnil** [comment]
Looks good, fix worked.

**Comment by doudar** [comment]
> Looks good, worked for me as well.

Awesome! thx! - merging

**Pull request merged**
