### PR TITLE
Ftms cadence

### PR DESCRIPTION
**Pull request by doudar**
Not to be merged yet.

### CODE REVIEW

**Comment by MarkusSchneider** [comment]
Hi, sorry was busy during the last day. Today I have time to make a test ride 👍

**Comment by doudar** [comment]
No problem! I've been busy as well lately. Thanks Markus

**Comment by MarkusSchneider** [comment]
Test was not successful ERG_Mode stopped. After switching power off and on everything start working again but failed after ~10 minutes.
I've create a log an take look at it tomorrow.

**Comment by doudar** [comment]
> Test was not successful ERG_Mode stopped. After switching power off and on everything start working again but failed after ~10 minutes. I've create a log an take look at it tomorrow.

Interesting...I wonder what we (I) broke :) lol

**Comment by doudar** [comment]
Hmm...so I just did a 14 minute ERG test and of course it didn't fail for me. (so i would have an idea where to look).

Here's my log, I'll check yours. 

Any chance the Enums take up substantially more heap and we need to increase task size?
[ss2k_log.txt](https://github.com/doudar/SmartSpin2k/files/7928937/ss2k_log.txt)

**Comment by MarkusSchneider** [comment]
Hi, my log:
[zwift_2022_01_24.zip](https://github.com/doudar/SmartSpin2k/files/7934498/zwift_2022_01_24.zip)

I'll add a memory trace to BLE_Server and enable memory trace in ERG_Mode and make a test to see if it is a heap problem.
What I can see is that no new Power Value is received from Zwift (search in log for FTMS_SERVER).

**Comment by doudar** [comment]
> FTMS_SERVER

One issue I see is that you did a lot of mixed cadence and it generated a weird power table:
N 656832 PowTab: "|   0|   0|   0| 161| 179| 269|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|"
N 656836 PowTab: "|   0|   0|   0|   88|   85|   91|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|"
N 656839 PowTab: "|   0|   0|   0|   96| 112|  -86|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|"

Those bottom resistance numbers should each be higher than the next reading left to right.

And the the anti knob-crash feature calculated the min position at:

N 661081 ERG_Mode: "PowerTable pairs [3][4]"
N 661091 ERG_Mode: "Min Position Set: -2"
N 661096 ERG_Mode: "Reverse/No Delta in PowerTable"

So that calculated limit may have prevented the knob from turning effectively if that was the symptom you saw. 

The bike that you're using must have a very sensitive knob that doesn't take many turns to adjust resistance? 

We may need to re-think how the auto min-max limit is calculated.

**Comment by doudar** [comment]
I also now see where it crashed on you:

N 1144882 BLE_Server: "00 73 -> 0x180d | 0x2a37 | HRS(HRM)[ HR(115) ]"
N 3551 HTTP_Server: "Waiting for connection to be established..."

**Comment by MarkusSchneider** [comment]
Did a test today and had some problems. Sometimes 0 Watts and 0 Cadence was sent to Zwift. Communication to Zwift was interrupted and blue led start flashing. I've added an option to disable UDP Logging. I'll try it tomorrow to see if this solves my problems.

What we can do with UPD log is to use a queue (same way it is done with BLE) and create another task with low priority to send all messages from the queue to udp socket. The queue must have a max count of queued messages to avoid high memory consumption if the worker is not fast enough to empty the queue.

**Comment by MarkusSchneider** [comment]
Another idea. 
Adding a filter (a list of identifier separated with spaces e.g ERG_Mode FTMS_SERVER) to filter the log-messages and send only matching messages via udp.
Empty filter sends all messages.

**Comment by doudar** [comment]
I'd really like one of us to play with that new library I found and see if it's compatible and can be used as a web socket. I think that  would solve most of these issues. 

For now, I propose we remove the UDP logging automatic toggle I put in place yesterday, and replace it with a static message in the http debug log that says "UDP Logging enabled. Please monitor UDP port 10000 for debugging messages."

After that's done, let's feature freeze FTMS-cadence branch, work on getting it stable for you, merge into develop and create a release. 

The branch has already been stable for me so we just need to figure out what is causing your issue. Is it possible that there's another FTMS power server in range that SS2K is connecting to and it's reporting zero cadence/power in between the other power server readings from you're ride?

I have that happen if there's another SS2K in my house and I don't have my BLE power connection set to my left pedal.

**Comment by MarkusSchneider** [comment]
Did a training today with disable UDP logging. Worked well. I also recognized that my BLE connection is weak. Had problems with my HR Belt. So I think the connection problems / missing values are related to the weak BLE.

We can merge this branch 👍

**Review by MarkusSchneider — APPROVED** [review]

**Comment by doudar** [comment]
> Did a training today with disable UDP logging. Worked well. I also recognized that my BLE connection is weak. Had problems with my HR Belt. So I think the connection problems / missing values are related to the weak BLE.
> 
> We can merge this branch 👍

Sounds great! I'm just about to push changes so that we show this when UDP logging is enabled, and then I'll merge.
image

**Pull request merged**
