### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by MarkusSchneider**
Ok, next try,

I've change the form submit behavior. Now I do the form.submit() inside of the confirmation function. Works on windows and android.

### CODE REVIEW

**Comment by doudar** [comment]
Thanks Markus - I’ll test this a bit later today

**Comment by doudar** [comment]
So unfortunately still the same results with iPhone. 😞

I tried to do a bunch of research on this but I can’t come up with anything meaningful.

**Comment by MarkusSchneider** [comment]
> So unfortunately still the same results with iPhone. 😞
> 
> I tried to do a bunch of research on this but I can’t come up with anything meaningful.

On IPhone if you press the Reset Button the Confirm Dialog pops up and if you press then cancle reset is submitted. Correct?

**Comment by doudar** [comment]
> Ok, next try,
> 
> 
> 
> I've change the form submit behavior. Now I do the form.submit() inside of the confirmation function. Works on windows and android. 

I've tried a few different things with returning "Success" when it tries to load /hotspot-detect.html but it doesn't seem to help even though the iPhone then thinks it's connected to the internet. 

Trying via the captive portal with no internet:
https://user-images.githubusercontent.com/17362216/147898695-184d2f29-8540-4428-9d3c-82185e2a865c.MOV

Trying via Safari with no internet:
https://user-images.githubusercontent.com/17362216/147898721-e9d62867-57fe-43d9-ad3a-7d58f0638d70.MOV

**Comment by MarkusSchneider** [comment]
Is this eventual a browser cache problem? I've changed the title of the Settings page. You can now see if new page is loaded.

**Comment by doudar** [comment]
> Is this eventual a browser cache problem? I've changed the title of the Settings page. You can now see if new page is loaded.
> 
> 

https://user-images.githubusercontent.com/17362216/147959786-c8aa4626-fa07-422c-b85e-cded5400bd15.MOV

**Comment by doudar** [comment]
> > Is this eventual a browser cache problem? I've changed the title of the Settings page. You can now see if new page is loaded.
> 
>  Upload.from.GitHub.for.iOS.MOV

Should we just do a workaround with Javascript wheras if useragent == webkit/iOS && ping 8.8.8.8 unsucessful -> don't popup confirmation?

**Comment by MarkusSchneider** [comment]
Hi Anthony,
I've removed the default confirmation dialog and added a custom one. 
If this not work on you IPhone consider to buy a new mobile 😁.

Don't thought that a simple confirm dialog would be challenging 😂.

I hope this works. Sorry that I have to bother you with all the testing.

Greetings
Markus

**Comment by doudar** [comment]
LOL!!! 

I'll give it a try! 

I see you've been very busy today!

**Comment by doudar** [comment]
Yay! We have a winner!

Also, I see the phone occasionally requests HTTP_Server: "Link Not Found: proxy-safebrowsing.googleapis.com:443" so maybe that was part of our issue?

The world may never know!

**Review by doudar — APPROVED** [review]
It works!!!

Go ahead and merge it if you're all done with this branch Markus.

**Pull request merged**
