### PR TITLE
Serial test

### PR DESCRIPTION
**Pull request by doudar**
Added Peloton serial data to the sensor factory. 

Not tested on an actual bike. Not ready to be merged. WIP

EDIT: Initial testing completed. Waiting on secondary testers and then we will finally have Peloton hardware support :)

### CODE REVIEW

**Comment by doudar** [comment]
Initial testing is going great. Will do a full ride tonight.

**Comment by doudar** [comment]
Latest Binary:
[firmware.zip](https://github.com/doudar/SmartSpin2k/files/9856286/firmware.zip)

**Comment by doudar** [comment]
Passing along testing to @eMadman . Once that's completed, merging to develop!

**Comment by eMadman** [comment]
Awesome!  Going to get my cable made for testing this weekend

**Comment by eMadman** [comment]
I've done two test rides so far - both relatively flat.  One sim, another with Erg.  

Results are extremely promising so far.  I'd like to get in one more with bigger, steeper hills or bigger jumps in power zones.

**Comment by chaloney** [comment]
Is the cable needed for this the same as the one used for the gymnasticon?ptx2/gymnasticon: Make obsolete and/or proprietary exercise bikes work with popular cycling training apps like Zwift, TrainerRoad, Rouvy and more.github.comSent from my iPhoneOn Nov 9, 2022, at 8:54 AM, eMadman ***@***.***> wrote:﻿
I've done two test rides so far - both relatively flat.  One sim, another with Erg.
Results are extremely promising so far.  I'd like to get in one more with bigger, steeper hills or bigger jumps in power zones.

**Comment by doudar** [comment]
`Isthe cable needed for this the same as the one used for the gymnasticon?ptx2/gymnasticon: Make obsolete and/or proprietary exercise bikes work with popular cycling training apps like Zwift, TrainerRoad, Rouvy and more.github.comSent from my iPhoneOn`

@chaloney :
Yes, basically the same cable. The intent is for this to work with our new board (that requires no/minimal soldering) which is in the final testing phases and can be ordered either via JLCPCB or from one of us (whoever wants to pay the setup fee and keep the boards stocked). We're not quite certain what the price point will be on the boards yet but I'd like to keep it reasonable. This isn't a money making venture for any of us but we do need to cover our development costs lest we incur the wrath of our SO's. 

Because it requires a level converting UART->Serial driver, we don't have a complete DIY solution yet (without the integrated PCB) but it would be 100% doable. If anyone wants to take up the challenge of putting together a DIY guide, I'd gladly work with them on providing the required information. The PCB development was accomplished with the help of Purdue University Senior Design Class!

If you're interested in being an early adopter, I'll be sending some boards to @eMadman very soon for more testing and potentially a couple kit customers. He is also sourcing some pre-made cables to go along with the boards making the whole thing a print-plug-play setup. 

Here's a photo of our latest test batch!

image

image

image

**Comment by chaloney** [comment]
Thanks for the detailed response. I have a gymnasticon that I currently use with trainer Road on my phone. I have been hoping to use It with a smart spin 2k to make my peloton into a stand-alove swart bike but have been having trouble getting the 3d printed gears to mesh properly ( version 1 case and non-pic). Would I be able to use the cable from the gymnastion & my current ss2k with the firmware from this pull-request (assuming I can figure out the other problems I’m having)?  Obviously I’d have to make an entry point in the case for the cable to get to the esp-32 dev board.

**Comment by doudar** [comment]
You could breadboard it according to the rev_2 pinout in the current settings.h in the include directory. You'll also then need to apply 3.3v to gpio 34 so that the firmware recognizes the setup as "revision 2". 

Then I'd recommend wiring the txd and rxd according to the diagram DFC has https://github.com/intelligenate/dfc/blob/main/img/arduino-circuit.png

The tip can be left disconnected if you're using the head unit in peloton mode. If you're screencasting Zwift or another program to the peloton like we do, you can unplug the headunit and connect txd on the SS2K. SS2K will then request the bike to send power and cadence without having to be in a workout on the peloton. 

Both the Peloton TXD (tip) and SS2K TXD cannot be connected at the same time because they interfere with each other.

**Review by eMadman — COMMENTED** [review]
Tested on multiple rides between sim mode and erg mode.  Flashed on a previous gen PCB to confirm functionality there.

Can't think of much other way to break it so it looks good!

**Review by eMadman — APPROVED** [review]

**Comment by chaloney** [comment]
Sorry for the very delayed response. I am very interested in this but I was getting ready to move and had no idea how long it would be before I had my peloton back in working order. It is now up and running and I’d love to find out more about the fully integrated device. As I implied, I use a gymnasticon to send power and cadence from the peloton to my SS2K v1 to use primarily with TrainerRoad which seems to be working perfectly (only one ride since getting it all set up). I ditched the peloton screen for a 24” smart tv as I could not (despite countless hours of trying) get any apps to install on the peloton - works great, even has voice control through the amazon fire tv remote. Doing so I discovered that the 12v power supply for the peloton screen fits and appears to power the SS2K- haven’t tried this while riding yet but it may simplify the tangled mess of cords I have a bit, as will eliminating the need for the gymnasticon. Please let me know if any boards are available. I will be happy to take pics of my build - plan to get my 3d printer up and running next week and have already located my soldering iron so I should be able to get started when I’m able to get a board. I’m still amazed at the ingenuity of this project. I remember reaching down to spin the resistance knob when I was first trying out TrainerRoad using the peloton and the gymnasticon and wondering if this kind of thing would be possible, but knowing it would be way beyond my capabilities to create. I’m very glad that I wasn’t the only one thinking along those linesThanks,Matt RossingSent from my iPhoneOn Nov 9, 2022, at 8:58 PM, Anthony Doud ***@***.***> wrote:﻿
Isthe cable needed for this the same as the one used for the gymnasticon?ptx2/gymnasticon: Make obsolete and/or proprietary exercise bikes work with popular cycling training apps like Zwift, TrainerRoad, Rouvy and more.github.comSent from my iPhoneOn
@chaloney :
Yes, basically the same cable. The intent is for this to work with our new board (that requires no/minimal soldering) which is in the final testing phases and can be ordered either via JLCPCB or from one of us (whoever wants to pay the setup fee and keep the boards stocked). We're not quite certain what the price point will be on the boards yet but I'd like to keep it reasonable. This isn't a money making venture for any of us but we do need to cover our development costs or incur the wrath of out SO's.
Because it requires a level converting UART->Serial driver, we don't have a complete DIY solution yet (without the integrated PCB) but it would be 100% doable. If anyone wants to take up the challenge of putting together a DIY guide, I'd gladly work with them on providing the required information. The PCB development was accomplished with the help of Purdue University Senior Design Class!
If you're interested in being an early adopter, I'll be sending some boards to @eMadman very soon for more testing and potentially a couple kit customers. He is also sourcing some pre-made cables to go along with the boards making the whole thing a print-plug-play setup.
Here's a photo of our latest test batch!

**Comment by eMadman** [comment]
@chaloney email me at emadmanmakes@gmail.com and we can talk about options there.  I can send you a fully assembled one or the PCB and breakout cable for you to DIY the case.  I've got some b stock parts that might actually be suitable for you since you're not using the screen.

Here it is in action on my bike:
https://youtu.be/S3yOk56pnr4

**Pull request merged**
